#
# This source file is part of the XCTHealthKit open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest_ios:
    name: Build and Test Swift Package iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: XCTHealthKit
      artifactname: XCTHealthKit.xcresult
  buildandtestuitests_ios:
    name: Build and Test UI Tests iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: Tests/UITests
      scheme: TestApp
      artifactname: TestApp.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest_ios, buildandtestuitests_ios]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: TestApp.xcresult XCTHealthKit.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
